/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import Modelo.Conexion;


public class Detalle_Produ extends javax.swing.JInternalFrame {

    public Detalle_Produ() {
        initComponents();
        PreparedStatement ps;
            ResultSet rs;
            Conexion con=new Conexion();
            Connection acceso;
            try{
           DefaultTableModel modelo=new DefaultTableModel();
           Tabla.setModel(modelo);
           acceso=con.Conectar();
   String sql="select codigo, nombre_producto, tipo_producto, existencia, precio_adquirido, precio_vender from productos"; 
  ps=acceso.prepareStatement(sql);
    rs=ps.executeQuery();
     ResultSetMetaData rsMd=rs.getMetaData();
     int cantidadColumnas= rsMd.getColumnCount();
     modelo.addColumn("codigo");
     modelo.addColumn("Nombre del producto");
     modelo.addColumn("Tipo de producto");
     modelo.addColumn("Existencia");
     modelo.addColumn("Precio adquirido");
     modelo.addColumn("Precio a vender");
 
     while (rs.next()){
         Object[] filas=new Object[cantidadColumnas ];
for (int i=0;i<cantidadColumnas;i++){
    filas[i]=rs.getObject(i+1);
}
modelo.addRow(filas);
     }
     
         }catch (SQLException ex){
           System.err.println(ex.toString());   
         }
    
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        setClosable(true);
        setTitle("Detalles del producto");

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre del producto", "Tipo de producto", "Existencia", "Precio adquirido", "Precio a vender"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
